name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Upload to Azure Blob Storage
      run: |
        az storage blob upload-batch -d '$web' -s . --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
